name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tgymnich/publish-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
